### ISSUE TITLE
Issue tracking link is incorrect

### ISSUE THREAD

**Issue by theres-waldo** [WICG/scroll-boundary-behavior#20]
The "issue tracking" link in the spec is:

https://github.com/majido/scroll-boundary-behavior/issues/

but the issue tracker being actually used is:

https://github.com/WICG/scroll-boundary-behavior/issues

**Comment by bgirard** [comment]
I forgot to check this in but I have a root level script 'bikeshed.sh' scrip that generates index.html using the following:
```bash
curl https://api.csswg.org/bikeshed/ -F file=@index.bs -F force=1 > index.html
```

@majido Do you have any idea why the file you generated included a Github link when none is specified in the markup? Is the script hosted at the endpoint above perhaps out of date? When I generate with the above I don't get Issue Tracking section.

**Comment by majido** [comment]
I use a local bikeshed setup instead of the API. Bikeshed generates that link based on the [Repository metadata](https://tabatkins.github.io/bikeshed/#metadata-repository) which we don't have specified. Also when not specified, bikeshed infers that from `git remote` of the current repo automatically. 

So in your case of using the URL, it doesnot generate anything. In my case of using my local git forked repo it uses that. The solution is to specify the repo and avoid this automatic behavior. 

Thanks for the report! I will send a PR to fix this as suggested above.

**Comment by majido** [comment]
https://github.com/WICG/scroll-boundary-behavior/commit/bf1b358c957ee3070a4c786d8902ead7f4871749
