### ISSUE TITLE
scroll-boundary-behavior name is long and hard to spell

### ISSUE THREAD

**Issue by birtles** [WICG/scroll-boundary-behavior#24]
Continuing discussion from https://github.com/w3c/csswg-drafts/issues/769 here, as suggested.

I'm not sure if `scroll-boundary-behavior: none` is logical. It suggests there is no behavior, but there is behavior (the behavior defined for `none`). `scroll-overflow: none` or `scroll-chaining: none` seem better to me at least in that regard.

CC @bgirard, @ChumpChief, @majido

**Comment by ChumpChief** [comment]
On the previous thread we seemed to have agreement that this API replaces the proposed `overscroll-action`, which would free that terminology up for use.  I think "overscroll" is a reasonable shortening of "scroll-boundary" (and maybe more descriptive in a sense, since it's specifically about the action of scrolling past the boundary, rather than the boundary itself).  So a few options in that vein might be:

* `overscroll-action`
* `overscroll-behavior`
* `overscroll-effect` (though "contain" sounds more like an "action" or "behavior" than an "effect" to me)

I'd be fine with any of these three, but that said I'm also satisfied by `scroll-boundary-behavior`.  I don't like `scroll-overflow` since it bears no mention of the edge/boundary of the overflowed content or action of overscrolling, which is at the core of the feature's behavior.

**Comment by birtles** [comment]
`overscroll-` is pretty good. Even `overscroll-behavior` isn't so bad since at least it parallels `scroll-behavior`.

**Comment by majido** [comment]
My opinion is mostly aligned with Matt's [earlier comment](https://github.com/w3c/csswg-drafts/issues/769#issuecomment-337082123) in that I do think being consistent with `scroll-behavior` is actually a positive thing. So I like to keep `-behavior` suffix. This is despite the fact that I am also a a non-US speller. I think consistency here trumps this minor historical quirk.

However, having a nice shorter name is also nice and using `overscroll` is reasonable to me as it was also the original naming. So in theory +1 for `overscroll-behavior`. 

In practice, I am just a bit worried about changing the name rather late specially given that TAG and other participants didn't have any negative feedback on the name. Also another practical concern is that we are aiming to ship this in Chrome M63 and the window to land changes in there is closing soon.

But if there is strong consensus here (@bgirard do you have any objection against `overscroll-behavior`?) then I am fine with pushing the change on Chrome and propose that to TAG.








We have

**Comment by tabatkins** [comment]
I'm in general against `-behavior`—like `-mode`, it's a zero-information word that can be added to most CSS properties without changing their meaning.

But if we must retain consistency with `scroll-behavior`, then `overscroll-behavior` sounds good—it invokes the correct notion better, I think, and is much shorter.

> In practice, I am just a bit worried about changing the name rather late specially given that TAG and other participants didn't have any negative feedback on the name. Also another practical concern is that we are aiming to ship this in Chrome M63 and the window to land changes in there is closing soon.

The spec hasn't shipped anywhere, it's utterly changeable.

**Comment by bgirard** [comment]
I also like `overscroll-behavior` and agree with the consistency with `scroll-behavior`. And since it's not too late to change it, I think we should.

Does anyone object to changing it?

**Comment by majido** [comment]
Let's go ahead an change it to `overscroll-behavior`.

**Comment by theres-waldo** [comment]
I'm fine with `overscroll-behavior`. (I like `overscroll` even better, but I see `overscroll-behavior` seems to have consensus, so I'm happy to go with that.)
