### ISSUE TITLE
How should a contain/none element behave if it is handed off scrolling from one of its descendant?

### ISSUE THREAD

**Issue by bgirard** [WICG/scroll-boundary-behavior#3]
Imagine you have the following scrollable divs:
```
<div id=d1>
  <div id=d2 style='scroll-boundary-behavior: contain'>
    <div id=d3>
      <div id=d4>
      ...
```
And the user scrolls d4 to its boundary. The user agent decides to hand off scrolling to d3 which hands of scrolling to d2.

I would expect scroll chaining to happen in d4, d3 but stop at d2. Does anyone disagree?

**Comment by ChumpChief** [comment]
I do agree that any scrolling initiated by d2 or any descendants must not chain to d1.

>The user agent decides to hand off scrolling to d3

I think this scenario is just stating that if the UA does choose to chain d4->d3->d2 then blocking d2->d1 is the expected behavior, rather than mandating that d4 must chain to d3, but just wanted to make sure.  There's no guarantee that the UA will chain from d4->d3 in this scenario (e.g. most UAs will not chain out of d4 for keyboard scrolling).

I don't think multichain has any unique characteristics from any other reason that d2 might scroll -- if d2 scrolls for any reason and reaches its boundary then the behavior should be honored.

**Comment by bgirard** [comment]
Yes I agree that it's not unique and probably didn't need any special mention but I added it to be precise. A difference in implementation here would be painful. I wrote the definition of contain to be explicit:

This value indicates that the element must not perform scroll chaining **to any ancestor along the scroll chain regardless of whether the scroll originated at this element or one of its descendants**. This value must not modify the overscroll behavior.
