### ISSUE TITLE
Should contain apply to a potentially scrollable element without a scrollbox

### ISSUE THREAD

**Issue by bgirard** [WICG/scroll-boundary-behavior#4]
See: https://www.w3.org/TR/cssom-view-1/#potentially-scrollable

Say you have a potentially scrollable element that doesn't have a scrollbox. This could be a fixed/absolute position scroller such as a chatbox on a site like Facebook/Gmail. There's not yet enough content for it to overflow and have a scrollbox however it may soon overflow once more content is added. How should scroll-boundary-behavior apply to such an element?

The spec could:
* require contain/none to disable scroll chaining for potentially scrollable elements even without a scrollbox. This gives a consistent user experience since the behavior doesn't depend on if there's a scrollbox or not. Scrolling over a chatbox on a page for example will never handoff scrolling to the parent element. The user will always get the same scroll chain behavior without care.
* require contain/none to leave the scroll chaining unmodified for an element without a scrollbox.
* leave it undefined. Not ideal.

I'm leaning towards the first option but not strongly.

**Comment by bgirard** [comment]
Similarly what if the element is not potentially scrollable at all?

**Comment by ChumpChief** [comment]
I also prefer the first option.  By default, Edge provides a bounce effect for potentially scrollable elements if there is no better element to chain to in its ancestor chain (e.g. the body is the most common scenario).  A developer would probably want the ability to suppress that depending on their scenario.  I think Safari on iOS has similar behavior, at least for the body.

I don't think the property should have any effect if applied to an element with no potential to scroll.  My mentality of the feature is "When this element is scrolled, and it reaches its boundary, what behavior should occur?"  Since elements with no potential to scroll are never actually scrolled, that statement never applies for them.  Whereas potentially scrollable elements are in fact scrolled, they just hit their boundary immediately due to their short content.

**Comment by majido** [comment]
+1 to @ChumpChief suggestion. 

I think you may want to use the [scroll container](https://drafts.csswg.org/css-overflow-3/#scroll-container) definition from css-overflow module instead of [potentially scrollable](https://drafts.csswg.org/cssom-view/#potentially-scrollable) in cssom. The **potentially scrollable** seems to consider the `clip` value as potentially scrollable but I don't this we should have any boundary behavior in that case as it is not scrollable either by user or programmatic.

**Comment by bgirard** [comment]
I agree. Using `scroll container` will mean that this property will apply to all elements that have overflow set to auto/hidden but that don't currently overflow.

This can be useful to keep a consistent behavior for elements that are changing size dynamically and oscillate between having overflow and not.

It also means that you could add `overflow: hidden; scroll-boundary-behavior: contain;' in an arbitrary node in the hierarchy if you want it to block scroll chaining. This can be useful if you can't easily get at the right scrollable node from the current abstraction.

I'll make this change.
