### ISSUE TITLE
Should contain/none mandate that the user agent disables scroll chaining?

### ISSUE THREAD

**Issue by bgirard** [WICG/scroll-boundary-behavior#5]
In the current proposal I wrote that it's not mandatory for the user agent to disable scroll chaining. My reasoning is that for certain input modes the user agent may decide that it's necessary for some kind of scroll chaining to occur. It could otherwise lead to the user's view being 'stuck', at least with respect to a particular input mode.

Imagine a device (eg. a phone) with a small screen and a low resolution with only a touch input mode. A 'scroll-boundary-behavior: contain' element covers the entire screen and the user needs to scroll to bring the navigation/URL bar back into view or to trigger a navigation action. In this case the user agent might decide to allow scroll chaining. It may chain scrolling directly to the navigation bar or the navigation gesture if the user agent decides that it's more appropriate for the input mode.

I think it's better to use 'should' rather then 'must' and to leave examples where a user agent might chose to ignore the hint.

**Comment by ChumpChief** [comment]
I'm in favor of a "must" requirement.  Developers using this feature are presumably doing so because their site/app depends on a high level of control over the scrolling behavior.  They are also probably already using the current popular methodology of preventDefault on relevant scrolling mechanisms and driving the scroll in script.

Allowing scroll-boundary-behavior to be inconsistent and non-interoperable due to leniency in the spec seems likely to hinder adoption, as developers' current preventDefault implementations don't suffer from these problems.  A "must" requirement would be no worse than their current behavior in the scenario you describe.

**Comment by bgirard** [comment]
I've been looking for a good definition of default actions for events that can trigger scrolling but I could just find references that the default action could be scrolling or zooming for some events. I agree that the spec should not mandate anything weaker than preventDefault otherwise web authors will add a non-passive listener just to be safe and it will defeat the purpose.

I just want to be careful about not specifying a behavior that is also much stronger and stricter than preventDefault.

I am leaning towards 'must' now so I'll write my draft with 'must'.

**Comment by staktrace** [comment]
I like that in the spec you explicitly state the behaviour should be at least as strong as preventDefault(). In Fennec for example we'll probably want to still allow the toolbar to scroll into view, even if all the scrollable elements have 'none' as their boundary behaviour. However this is just as "strong" as what we do with preventDefault(), since even if the author preventDefault()s the touch events we still allow scrolling the toolbar into view. (As bgirard said, this is to prevent the web page from trapping the user and even possibly spoofing the URL bar).

With respect to the spec, I doubt it makes much difference in practice whether you use 'must' or 'should' - the intent is pretty clear, and whether implementations are technically in compliance with the exact wording of the spec or not - I don't think many people care as long as the follow the spirit of the spec.

**Comment by bgirard** [comment]
I would rather if implementations were in compliance with the exact wording so if we can clear it up it would be great. Otherwise it's a buggy specification.

As I understand it, specifications often relate to the rendering of the document and thus I would think that the chrome, not being part of the document, doesn't have to follow the behavior outlined in spec since they are not part of the document. I'm not sure if that interpretation is correct. The line is muddied with HTML based chromes.

I guess the spec is just as accurate as the spec for preventDefault. I'm probably overthinking it:
https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-Event-preventDefault

**Comment by majido** [comment]
> As I understand it, specifications often relate to the rendering of the document and thus I would think that the chrome, not being part of the document, doesn't have to follow the behavior outlined in spec since they are not part of the document.

I think this is a correct interpretation. In particular browser's toolbar/navigation-bar scrolling happens before the event is even delivered to the content which means that "preventDefault()" cannot prevent it either. So even with "MUST" requirement the browsers are able to scroll the top navigation bar while complying to the spec the same way. 

I agree that we should match the power of "preventDefault()" here and use "MUST". It is easier to relax the requirement than the opposite direction if there is evidence it is needed.

**Comment by bgirard** [comment]
Ok the current wording then is fine as-is I believe. Let me know if you want any edits.
Normative:
`This value indicates that the element must not perform scroll chaining`

Non-normative note:
`Note: This property should provide guarantees that are, at least, as strong as preventDefault for preventing both scroll chaining and overscroll. Doing otherwise would cause content authors to use preventDefault instead.`
